### ISSUE TITLE
Any way to use word wise with azw3 format?

### ISSUE THREAD

**Issue by bachmx** [tmilovanov/wisecreator#9]
I love wisecreator. It's very useful forme. But in some books, i want to use some html5 and css3 featureds. So any way to use word wise with azw3 format? 

Thank you!

**Comment by tmilovanov** [comment]
@bachmx Hello!
It's planned to add azw3 support some time, but I can't tell you exactly when.

**Comment by bachmx** [comment]
Thank you very much! Hope it will come soon!

**Comment by hwanjongyu** [comment]
@tmilovanov I'm really expecting to this feature.
I tried to remove newline of KF8's rawml, but it didn't help.
I hope that you know the differences between mobile and azw3 and fix it soon.
Thanks.

**Comment by otherguy** [comment]
+1!

Haven't looked at the code yet but is the wordwise sqlite DB embedded in the mobi? If not, wouldn't it work to first convert all books to mobi, generate the wordwise database and then convert them to azw3 (or just ignore that step if they were originally in azw3 format anyway)?

**Comment by tmilovanov** [comment]
@otherguy 

No, wordwise DB isn't embedded into the mobi. I haven't tried the way you suggest, but it would be interesting if you try. But I suspect that it wouldn't work, because wordwise DB contains raw offsets in bytes to the each word it explains. I don't know how azw3 stores the text, but if offset change during convertation it wouldn't work. Even if you convert mobi to mobi it often doesn't work properly.

**Comment by otherguy** [comment]
Ah I see... then it definitely will not work.

AZW3 support should not be so hard though. It's basically epub in a different container...

**Comment by zetavg** [comment]
I just did some experiments on my `azw3` books and found something interesting:

- Instead of removing the new lines in `rawml` as @hwanjongyu mentioned, I adjusted `word_offset` (aka the `start` column in database) to `+411` for page one (precisely, `xhtml` file one), `+548` on page two and `+1380` for page three. It works.
- `word_offset` on each page should be shifted by a different constant to get the correct result. That constant remains the same for the whole page, so if you find that constant, you can make a whole page work.

I haven't tested it on other `azw3` books yet, so I'm not sure if the three constants above works globally or is something related to the book I'd tried on.

<details>
<summary>Here's what I did to find those constants</summary>


1. Grab a bunch of unique words that would be considered unfamiliar by Word Wise. I collect some from `log.txt` when `DEBUG = True`:

```
edition programmer purely variable recursive copyright attribution instal aka conversion auto robust bane download interact optional configuration viewer execute intuitive compatible vista flavor contribute doc convention simplify database manipulate metadata kindle kobo nook graphical interface typical principal functionality utility installation greet wizard configure directory exclusive click default generic optimization congratulation downward arrow component icon respective panel browser toggle luggage tag juke navigate keyboard grid bookshelf indicator circular setup internet subset criterion query arguably noble mess domain lesser toolbar readable transition ray evolve audio tablet enhance proliferation exclusivity vendor proprietary publishing forum jumble straightforward complicate indent blank specialized description hover cursor explicitly layout attribute bold italic preserve poorly heuristic modification acronym resell unlimited handy determine seller partial removal tempt facilitate millennium circumvent circumvention silliness typo invaluable syntax preview embed font punctuation unused overlook integrate recipe subscription fetch scheduler convenient automatic disclosure triangle accord delete eject disconnect customize template gen folder replacement disable reorganize opus reorder unsupported unchecked bookmark navigation familiarize manual knowledgeable veteran bug pad align margin decimal
```

2. Edit a book, paste that bunch of unique words on the beginning and the end of each page (`xhtml` file).

3. Use `wisecreator/main.py` to convert the `azw3` book, and copy it to Kindle.

4. Open the book on Kindle, go to the first page where those bunch of unique words is. Word Wise should be broken but there're still some words coincidentally fits some position of other words, so a Word Wise hint is shown. Touch the hint then we can see the original word, then use the positions of the two words to calculate the shift value.

</details>

I don't have any `azw3` book from Amazon that has Word Wise support (those have Word Wise are all `kfx`s), maybe someone can find out more by inspecting those books if they do have some.

**Comment by otherguy** [comment]
Unfortunately I don’t own any Amazon `azw3` books, I just like to convert all my books to that format.

**Comment by xxyzz** [comment]
If anyone still need this, please check out my calibre plugin: https://github.com/xxyzz/WordDumb. I found this repo several months ago and thought it would be much easier to extend the features that calibre already has, like parsing books or sending books to device.

**Comment by tmilovanov** [comment]
Done in version 2.0 https://github.com/tmilovanov/wisecreator/releases/tag/v2.0
